### ISSUE TITLE
Support watch prefix recursively

### ISSUE THREAD

**Issue by mcandeia** [zen-fs/core#116]
I have been using the watch feature and I encountered a couple of limitations:

1. FileChangeInfo Type Not Exported: It seems the FileChangeInfo type is not exported or at least I couldn’t find it in the current exports. It would be great if this type was made available to make handling file change events more explicit and type-safe.

2. Watch Method Limited to a Single Directory: The current watch method appears to be limited to a single directory. It would be really useful if the watch method worked like the Deno watcher, allowing for recursive directory watching or broader file system watching, rather than being constrained to just one directory.

e.g. https://docs.deno.com/api/deno/~/Deno.watchFs

**Comment by james-pre** [comment]
Thanks for submitting an issue. Allow me to address the points you brought up:

1. `FileChangeInfo`

`FileChangeInfo` is currently being imported from `node:fs/promises` ([source](https://github.com/zen-fs/core/blob/v1.0.11/src/emulation/promises.ts#L5)). While I'm all for compatibility, I would rather have the type be imported directly, rather than users using a re-export, which I feel adds needed complexity.

2. `watch` single directory limitation

Node's watch methods seem to have a `recursive` option (albeit, `false` by default). Due to the difference in the default value, an implementation would most likely follow Node's default of `false`.

This is not currently implemented in ZenFS, so I'll look into implementing this.

**Comment by mcandeia** [comment]
Thank you for your quick response and for addressing the points!

- FileChangeInfo:
I completely understand the preference for avoiding re-exports and agree that directly importing the FileChangeInfo type from the source (e.g., node:fs/promises) would be cleaner. I didn't realize that is coming from node:fs/promises because it relies only on `filename`

- Watch Single Directory Limitation:
That makes sense, especially regarding alignment with Node's default of recursive: false. I appreciate you looking into implementing this.

One thought regarding the recursive option: if recursive is enabled, it seems necessary to include the full file path in the event data, otherwise it might be difficult to determine which file in the directory tree was modified. Without the full path, it could be challenging to track changes effectively across nested directories. Do you have any thoughts on how this could be handled?

**Comment by james-pre** [comment]
> One thought regarding the recursive option: if recursive is enabled, it seems necessary to include the full file path in the event data, otherwise it might be difficult to determine which file in the directory tree was modified. Without the full path, it could be challenging to track changes effectively across nested directories. Do you have any thoughts on how this could be handled?

This could be handled with relative paths. For example, if you watch `/home`, which has a subdirectory `smith`, and a file gets written to `/home/smith/example.txt`, the event's file name might be `smith/example.txt`.

I will look into how Node and Deno handle this situation since it will most likely be better to follow the same behavior as them.

**Comment by mcandeia** [comment]
> > One thought regarding the recursive option: if recursive is enabled, it seems necessary to include the full file path in the event data, otherwise it might be difficult to determine which file in the directory tree was modified. Without the full path, it could be challenging to track changes effectively across nested directories. Do you have any thoughts on how this could be handled?
> 
> This could be handled with relative paths. For example, if you watch `/home`, which has a subdirectory `smith`, and a file gets written to `/home/smith/example.txt`, the event's file name might be `smith/example.txt`.
> 
> I will look into how Node and Deno handle this situation since it will most likely be better to follow the same behavior as them.

I mean, yes, that approach makes sense for relative paths, and it does seem like a good way to handle the issue. However, since the goal is likely to maintain Node compliance, is it acceptable to adjust this behavior in ZenFS, or should you strictly follow Node’s current implementation? 

I admit that I'm not very familiar with Node approach, the Deno approach itself is pretty straightforward and I would be very happy with something similar

**Comment by mcandeia** [comment]
Well, according to the chat gpt the node approach is exactly how you mentioned, so you are fine! Looking forward for having this!

**Comment by james-pre** [comment]
Thanks for your interest in the project! I plan on implementing and releasing the feature this week in the 1.1.0 release with device files.

**Comment by mcandeia** [comment]
@james-pre 

I’ve been using zen-fs and would love to contribute.

I was thinking about the possibility of migrating the project to Deno and publishing it on the JavaScript Registry (JSR). I believe this could bring several benefits, such as leveraging Deno’s security model, built-in tooling, and faster deployments via JSR. https://jsr.io/ (and even have support to npm out-of-the-box)

Do you see any potential issues or concerns with such a migration? I’d be happy to work on this if you're open to it.

Also, if you’d like to chat more directly about the project, do you have a Discord handle or another preferred method of communication? I’d love to collaborate further!

**Comment by mcandeia** [comment]
A bit about me: I'm a developer from https://deco.cx/ and we are building a new product https://webdraw.ai/ which will be backed by fs-like APIs on top of https://github.com/deco-cx/actors, I found zen-fs a perfect fit to integrate with https://github.com/isomorphic-git/isomorphic-git and actors. We can discuss more if you are interested to, looking forward for your responses.

**Comment by james-pre** [comment]
> Do you see any potential issues or concerns with such a migration? I’d be happy to work on this if you're open to it.

I would prefer if there was a minimal amount of tooling changes required, and think that would be one of the key factors in deciding whether to publish on JSR as well. For now, Deno 2.0 has full support for NPM modules so there is not a large barrier for entry.

> Also, if you’d like to chat more directly about the project, do you have a Discord handle or another preferred method of communication? I’d love to collaborate further!

Sure, my discord username is `alsovo`.

**Comment by mcandeia** [comment]
I have this minimal repro code that shows watch seems not to be working

```ts
import { InMemory, fs as mnt } from "@zenfs/core";
import * as fs from "@zenfs/core/promises";

const db = InMemory.create({ name: "tmp" });
await db.ready();
mnt.mount("/tmp", db);

const ctrl = new AbortController();
const watcher = fs.watch("/tmp", {
  recursive: true,
  signal: ctrl.signal,
});
const arrived = Promise.withResolvers<unknown>();
(async () => {
  for await (const event of watcher) {
    arrived.resolve(event);
  }
})();

await fs.writeFile("/tmp/xpto.txt", "xpto", { encoding: "utf-8" });

const evt = await arrived.promise;
ctrl.abort();
console.log(evt);
```
