### ISSUE TITLE
rm is not compliant with nodejs API

### ISSUE THREAD

**Issue by mcandeia** [zen-fs/core#121]
nodejs rm with force arg does a no-op operation when directory does not exists
```tsx
import * as fs from 'node:fs/promises';

await fs.rm('./xpto', { recursive: true, force: true });
```

but currently, rm requires a `stat` https://github.com/zen-fs/core/blob/main/src/emulation/promises.ts#L941 which can throws ENOENT that is not being caught. 

Suggestion: Catch ENOENT errors and do a no-op in case of non-existent file/directory when `force: true` is being used

**Comment by james-pre** [comment]
Fixed, I'll release this tomorrow.

**Comment by mcandeia** [comment]
thanks @james-pre
