### ISSUE TITLE
RangeError: Array buffer allocation failed when mounting the indexeddb partition

### ISSUE THREAD

**Issue by Artawower** [zen-fs/core#123]
When trying to write a relatively large number of files (over 600) to indexeddb and reloading the page in a web browser, I get a mount error:

```
chunk-3CTS4YNX.js?v=fa2b0238:9430 Uncaught RangeError: Array buffer allocation failed
    at new ArrayBuffer (<anonymous>)
    at PreloadFile._write (chunk-3CTS4YNX.js?v=fa2b0238:9430:44)
    at PreloadFile.writeSync (chunk-3CTS4YNX.js?v=fa2b0238:9465:31)
    at AsyncFS.crossCopy (chunk-3CTS4YNX.js?v=fa2b0238:14045:20)
    at async AsyncFS.crossCopy (chunk-3CTS4YNX.js?v=fa2b0238:14062:9)
    at async AsyncFS.crossCopy (chunk-3CTS4YNX.js?v=fa2b0238:14062:9)
    at async AsyncFS.crossCopy (chunk-3CTS4YNX.js?v=fa2b0238:14062:9)
    at async AsyncFS.ready (chunk-3CTS4YNX.js?v=fa2b0238:13961:9)
    at async resolveMountConfig (chunk-3CTS4YNX.js?v=fa2b0238:13843:3)
    at async configure (chunk-3CTS4YNX.js?v=fa2b0238:13877:35)
Show 3 more frames
```

This error is not reproduced when the number of files is small
`supressed` property is empty in the error

reproduction example: https://stackblitz.com/edit/vitejs-vite-vghser?file=src%2Fmain.ts (just wait until the files are created, then reload the page with the browser console open.)

**Comment by james-pre** [comment]
@Artawower,

Thanks for opening an issue. From some research, this error seems like it could be due to an out-of memory issue or incorrect length. According to MDN,

> [`RangeError`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError)
>    Thrown in one of the following cases:
>
> `length` or `maxByteLength` is larger than [`Number.MAX_SAFE_INTEGER`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER) (≥ 253) or negative.
>        `length` is larger than `maxByteLength`.

[source](https://developer.mozilla.org/Web/JavaScript/Reference/Global_Objects/ArrayBuffer/ArrayBuffer#exceptions)

If you could provide the values used when attempting to create the `ArrayBuffer`, that would be very useful.

Here is the affected line: https://github.com/zen-fs/core/blob/d4969b5ee0865d3c2d82edecfaa621769cd66561/src/file.ts#L469

**Comment by Artawower** [comment]
The end value is 5125 (same as other files). This is the locale scope before the error occurred
[locale-scope.txt](https://github.com/user-attachments/files/17579947/locale-scope.txt)

**Comment by james-pre** [comment]
I've been unable to reproduce the error. Could you please let me know what platform (e.g. Chrome 128 or Node 20.6.1) you're using? Additionally, if you could try to reproduce the error on another platform, that would be great.

Thanks.

**Comment by Artawower** [comment]
> I've been unable to reproduce the error

In the example I gave, does the mount work without error on your machine?

I am using chrome, interestingly this error does not appear in firefox for example.. I also tried reproducing the problem on other platforms (windows/linux), the result is the same

In node environment I also don't see this error, however I don't know how to use IndexedDB mount in node, so I used InMemory approach, maybe that's the issue

Perhaps there are some additional steps I can help you with to reproduce the error?

**Comment by james-pre** [comment]
> In the example I gave, does the mount work without error on your machine?

Yes

> I am using chrome, interestingly this error does not appear in firefox for example.. I also tried reproducing the problem on other platforms (windows/linux), the result is the same

I am using Firefox, so that may be part of it.

> In node environment I also don't see this error, however I don't know how to use IndexedDB mount in node, so I used InMemory approach, maybe that's the issue

You'll need to import a polyfill.

> Perhaps there are some additional steps I can help you with to reproduce the error?

I think I can try to debug this on Chrome. Unfortunately, I suspect this is a vendor-specific limitation, not something inherently wrong with ZenFS' code. I'll let you know if I confirm the bug.

**Comment by james-pre** [comment]
Okay, I can confirm this is a problem with Chrome. *However*, it appears this isn't a problem with ZenFS but rather a limitation in V8. It looks like this error comes from [builtins-arraybuffer.cc!ConstructBuffer](https://github.com/v8/v8/blob/c07d8f220405f6c0cdf53c748e7c07fd7916f1d5/src/builtins/builtins-arraybuffer.cc#L105), and is caused when the "Allocation of backing store failed."

**Comment by james-pre** [comment]
@Artawower:
> Yes, that should help. But unfortunately there is 1 unfixable [bug](https://github.com/zen-fs/core/issues/123#event-15037215895 ) in the current file system, and it won't be fixed.

Just for clarification this isn't something that can be fixed within ZenFS. It is an inherit limitation of the browser. Trying to allocate another buffer would just fail. There may be something that can be done to reduce memory usage though.
