### ISSUE TITLE
`IndexedDB` not working in React-NextJS

### ISSUE THREAD

**Issue by afshawnlotfi** [zen-fs/core#130]
For whatever reason I see stuff is getting written to the zenfs IndexedDB database in Inspect Element however when the `writeFileSync` is removed the contents do not get loaded making me believe it is just using InMemory for the storage layer

```typescript
import fs, { configure } from '@zenfs/core'
import { IndexedDB } from "@zenfs/dom"


export function TestComponent() {


    useEffect(() => {
        const loadFile = async () => {
            await configure({
                mounts: {
                    '/projects': IndexedDB,
                }
            })

            if (!fs.existsSync('/projects/test.txt')) {
                fs.writeFileSync('/projects/test.txt', 'This will persist across reloads!')
            }

            const contents = fs.readFileSync('/projects/test.txt', 'utf-8')
            console.log(contents)
        }

        loadFile()
    }, [])
   
    return <></>
}
```

I tried `await configureSingle({ backend: IndexedDB });` as well and it didn't work for `/` path too.

**Comment by Z34D** [comment]
@james-pre Hey man, I stumbled over this issue because I have the same problem, just with Vite as framework.

Deps:
"@zenfs/core": "^2.2.3",
"@zenfs/dom": "^1.1.7"

Code:
```
await configure({
  mounts: {        
    '/home': IndexedDB,
  }
});
console.log("fs", fs.readdirSync('/home'));
fs.writeFileSync('/home/test.txt', 'You can do this anywhere, including browsers!');
const contents = fs.readFileSync('/home/test.txt', 'utf-8');
console.log(contents);
```

So if I use the IndexedDB, like in the original issue, it writes the changes to the DB but does not load them. If I change e.g. to WebStorage, it just works fine.
