### ISSUE TITLE
Missing `import` for `crypto` causes crash with Webpack libraries

### ISSUE THREAD

**Issue by lvcabral** [zen-fs/core#146]
In my `node.js` library (built with Webpack) I was getting the crash below, and I realized that both in `util.js` and `inode.js` the `crypto` object is used but there is no import. I patched with `import * as crypto from "crypto";` both files in my `node_modules` and rebuilt and it fixed the crash. 

![image](https://github.com/user-attachments/assets/6e18566a-347e-4e00-b9c8-0c21dfa73388)

I can push a PR with the fix if it helps.

**Comment by lvcabral** [comment]
The issue was caused because I was using Node.JS 18, upgraded to 20 and it was fixed. Closing the bug.

**Comment by james-pre** [comment]
@lvcabral If you want to use a version of Node before v19, you will need to import `crypto` and then attach it to the global scope.
