### ISSUE TITLE
Features request: Could you add support to use something like skypack or jsdevil?

### ISSUE THREAD

**Issue by frog-o** [zen-fs/core#156]
I like trying to create webpage on Android and can't build or use node. It would be nice if I was able to use and have instructions on using jsdevil or another cdn when it not possible to build. Currently at least this two cdn don't work (for me) or I could not get them to work by following skypack instruction they gave an error and when I researched the error it said it was often do to circular dependency. I tried many deferent version.I couldn't git anything to work. I looked at your package.json and there are dependency I can't get with skypack. Currently I am not that good of a javascript to fix this error on my own.

**Comment by james-pre** [comment]
Hi @frog-o, thanks for opening an issue.

For your use case, I suggest bundling (Esbuild is a good bundler).

While you may not be able to use Node or NPM in production, using some package manager compatible with the package.json (or using something like import maps) in development is a must.

I haven't used the tools/runtimes/libraries you mentioned, so I can't offer any help with them.

I don't think there are any problems with ZenFS, so I'm going to close this issue. Please reach out if you find any bugs with ZenFS.

Thanks.

**Comment by frog-o** [comment]
@james-pre 

just for your info, I am familiar with devmap and esbuild (I think I prefer tsx which uses esbuild in the background but that really not an option for new  Android Wich I am running), All most all options are lost when you don't have a build system or a console.  I found a solution though esm.sh works at this moment.  I think you're getting a little confused jsdevil and skypack are not library and neither is ESM.sh( Wich I found today Which is meant for dino , dino I believe was made by the same guy as node but was trying to fix some of what he felt was designed flaws and is a node rewrite take this just hear say thou  I am going by my memory Wich might be wrong. It  from something I read long ago and I have bad comprehension). Skypack and all the ones I mentioned allow you to run npm without you having to have node installed and it does all the polyfil and tree shrink and All that.  To me this makes a lot more sense then use npm unless you're using pnpm or fancy yarn settings or something funky like that you still have to have it downloaded for each web project you make. I like the thought of letting someone else do the tree shaking for you with there more power full server not like that matter though after first build it is cached. 

If you don't mind I ask you to try esm.sh out.  I know everything boils down to preference I just find it hard to believe people prefer to use complicated builds and just want to make sure you didn't miss understand me. I am horrible about my communication and jsdevil is not a library at least I don't think so.

**Comment by james-pre** [comment]
I've used esm.sh in the past, and I've seen it work very well for other use cases.

In any case, ZenFS is a library, and being compatible with every bundler and/or package manager is not feasible. If the bundler or package manager your using does not support ZenFS fully, you may want to open issue on that project. I'm happy to help you with any issues with ZenFS.

Please let me know what errors you are given, I might be able to do something to help.

**Comment by frog-o** [comment]
>

> I've used esm.sh in the past, and I've seen it work very well for other use cases.
> 
> In any case, ZenFS is a library, and being compatible with every bundler and/or package manager is not feasible. If the bundler or package manager your using does not support ZenFS fully, 

Thanks that is all I asked for, I don't think you should worry about being compatible with ever builder .    I just need one since I found esm.sh  that's good enough for me.I think it would be a shame if you don't try to support 1 of the( bundler that I mentioned)  wich  should in theory work for all since it really doesn't really need a bundler. It looks like at this moment (even though I have not got around to test it much) everything is working with esm.sh and all that needs is to make sure it keeps working and add instructions for it to your page.  Just another note it hard to copy and paste on Android (yes android is not a good platform to do programming but it is the only thing I feel comfortable using) that the reason I didn't put the error.  There is no point to it if you have no plans to fix ( don't  get me wrong) you have every right to do so . No one should have to work for free . If was me though, I would want to try to address the most usage cases I could that didn't require a lot of work That the reason I put things online.I want to help as many people as I can.

**Comment by james-pre** [comment]
I get what you're saying, though writing documentation for CDNs isn't very productive. If I wrote documentation for esm.sh, then I would also need to include documentation for all of the other CDNs: JSDelivr, Unpkg, cdnjs, and Skypack just to name a few. Moreover, documentation for using a CDN isn't really needed due to how easy most are to use.

If you encounter a problem with a CDN, it is up to them to fix. ZenFS isn't the problem in this case, there is nothing I can do to fix someone else's CDN. If you do find a problem with ZenFS, I'll do my best to fix it.
