### ISSUE TITLE
bug: safari <= 13.1 error on big integer literal

### ISSUE THREAD

**Issue by igorbrasileiro** [zen-fs/core#160]
### Issue
On older browsers that don't have BigInt constructor, cause SyntaxError: `No identifiers allowed directly after numeric literal`.
![image](https://github.com/user-attachments/assets/99a3ad32-b975-47fb-a31e-42660354d356).

### Possible Solution
Use the `BigInt` constructor instead of `${number}n`, because by doing this the bundlers can polyfill the BigInt constructor and it will work on older browsers.

### Environment
Browser: Safari 13.1
OS: macOS Catalina.

**Comment by igorbrasileiro** [comment]
This problems still happening because of readable-stream package that uses big integer literals

**Comment by james-pre** [comment]
@igorbrasileiro, I will take a look at submitting a PR to readable-stream, but no guarantees for when (or if) it will get merged by the maintainers.
