### ISSUE TITLE
Support latest Node FS API

### ISSUE THREAD

**Issue by dr-vortex** [zen-fs/core#24]
We must support up to Node v20.

Rather than changing the internals, it would be easy to implement some of these functions in the compatibility layer (e.g. with `rmSync`, we could easily write code that uses existing BFS internal code rather than implementing new internals for it).

- [x] Support <v8
- [x] Support v10
- [x] Support v12
- [x] Support v14
- [x] Support v15
- [x] Support v16
- [x] Support v17
- [x] Support v18
- [x] Support v19
- [x] Support v20 

Features:
- [ ] Implement watch methods (#6)
- [x] Implement streams (#4)

**Comment by dr-vortex** [comment]
- [ ] Implement watch methods (#6)
- [ ] Implement streams (#4)

**Comment by zardoy** [comment]
Super excited and looking forward for fs.copy and recursive option in mkdir/rm support! Is there any eta or it's just a roadmap (without eta yet)?

**Comment by dr-vortex** [comment]
Right now it's more of a roadmap though I'm really hoping to get it done in the next month or so.

**Comment by zardoy** [comment]
Hey @dr-vortex ! Have got any roadmap changes? I'm still looking forward to this one!

**Comment by dr-vortex** [comment]
@zardoy,

I've added all of the functions and types for Node 14 (not implementations though). Hopefully, I can add all of the functions and types up to Node 20 over the next few months.

**Comment by dr-vortex** [comment]
As of 8ad0335, all of the features up to Node v20 have been *added* but not *implemented*

**Comment by dr-vortex** [comment]
> zardoy reacted with confused emoji

@zardoy,

The signatures and functions have been added but just throw `ENOTSUP`

**Comment by zardoy** [comment]
> The signatures and functions have been added but just throw ENOTSUP

👋 

Sorry, I might be missing something, why don't add the implementation there? Isn't the implementation straightforward? IMO just copying types doesn't make any progress ☹️

Anyway let me know if there any progress towards adding new functionality, eagerly waiting for new releases

**Comment by dr-vortex** [comment]
@zardoy,

>  Isn't the implementation straightforward

Yes, though tedious.

> Anyway let me know if there any progress towards adding new functionality

I had a lot of extra time the past few days and finally sat down and implemented many of the unimplemented functions. They are available in [v0.9.0](https://github.com/zen-fs/core/releases/tag/v0.9.0). Now, all that needs to be implemented is `statfs` and the various `watch` functions.

Now that everything else is done, I'm will track those two features separately.

**Comment by james-pre** [comment]
> Anyway let me know if there is any progress towards adding new functionality, eagerly waiting for new releases

@zardoy, It's been a while. Just letting you know [1.0.0 Release Candidate 0](https://github.com/zen-fs/core/releases/tag/v1.0.0-rc.0) just released. Also, I have not forgotten about the other packages- I will spend some time on them before the 1.0 release.
