### ISSUE TITLE
Zenfs does not work with Vite

### ISSUE THREAD

**Issue by philipp-strack** [zen-fs/core#35]
Installing the @zenfs/core package and running "vite" yields the following error

Failed to resolve entry for package "@zenfs/core". The package may have incorrect main/module/exports specified in its package.json: Missing "." specifier in "@zenfs/core" package

**Comment by dr-vortex** [comment]
@philipp-strack,

Can you please include an example of the code?

**Comment by dr-vortex** [comment]
Got it I'll push out a patch later today.

**Comment by dr-vortex** [comment]
The fix is pushed to other repositories, so I'm closing this issue.
