### ISSUE TITLE
Link to ZenFS from BrowserFS readme

### ISSUE THREAD

**Issue by vednig** [zen-fs/core#46]
If it is , updated readme in BrowserFS or link to the ZenFS in BrowserFS issues would be grateful.

**Comment by dr-vortex** [comment]
@vednigm,

Thanks for submitting an issue.

All of the issues in BrowserFS have been linked here.

As for linking to here in the BrowserFS repository-- this is a fork.  While I still have write access to the BrowserFS repository, I don't think I should promote my fork over any others simply because of my access.

**Comment by vednig** [comment]
I believe this fork will be supported for any changes in bugs, JS or browser APIs in future hence new visitors could be informed that there is a fork in development due to which they can take decision what to use.
A lot of archived repo do this when maintainer is no-longer supporting the existing project. It is good for community.

**Comment by dr-vortex** [comment]
I agree. I'm going to pull @emeryberger into this conversation. He is currently administering to BrowserFS since jvilk does not have the time. I defer to Dr. Berger on whether this fork should be mentioned in the BrowserFS readme.

**Comment by dr-vortex** [comment]
@vednig, I recently updated the BrowserFS readme to include the deprecation notice and a link to ZenFS, which resolves this issue.

**Comment by emeryberger** [comment]
@dr-vortex please incorporate some of the info from the BrowserFS README, specifically the https://github.com/jvilk/BrowserFS?tab=readme-ov-file#citing part. Thanks.

**Comment by dr-vortex** [comment]
@emeryberger, does 382e770 include what you are looking for?

**Comment by emeryberger** [comment]
That's fine, thanks.
