### ISSUE TITLE
`StoreFS` operation ordering

### ISSUE THREAD

**Issue by dr-vortex** [zen-fs/core#57]
`StoreFS.sync` seems to be executed before `StoreFS.commitNew` is completed. If so, the parent's directory listing has not yet been put to the store, but sync is getting it and an exception is being raised.

From [discussion #5](https://github.com/orgs/zen-fs/discussions/5)

**Comment by dr-vortex** [comment]
Hey @atty303, are you still experiencing this issue?

**Comment by atty303** [comment]
I don't know because I am not using this code-passing feature right now. I think we can close this Issue.

**Comment by dr-vortex** [comment]
Sounds good.
