### ISSUE TITLE
How to transition from BrowserFS to ZenFs

### ISSUE THREAD

**Issue by chinonso098** [zen-fs/core#76]
My apologies for the mis-use of the Issue system, but sadly, GitHub doesn't have DMs

I'm currently working on a project that uses BrowserFS, I came across your comment on the BrowserFS repo and thought I would give ZenFS a try. I'm currently stuck on the configuration step for ZenFS

in BrowserFs, I have this

`   
        import osDriveFileSystemIndex from '../../../osdrive.json';
        import * as BrowserFS from 'browserfs';

         BrowserFS.configure({
                fs: "MountableFileSystem",
                options:{
                    '/':{
                        fs: 'OverlayFS',
                        options:{
                            readable:{fs: 'XmlHttpRequest', options:{index: osDriveFileSystemIndex}},
                            writable:{fs:"IndexedDB", options: {storeName: "browser-fs-cache"}}
                        },
                    },  
                }
            });

       const fileSys = BrowserFS.BFSRequire('fs');
`

[code](https://github.com/chinonso098/CheetahOS/blob/main/src/app/shared/system-service/file.service.ts)

osDriveFileSystem content is  this
{"osdrive":{"Desktop":{"audioplayer.url":null,"fileexplorer.url":null,"heat.url":null,"hello.url":null,"taskmanager.url":null,"videoplayer.url":null},"Documents":{}, "simple.txt":null}}

How do I transition this to ZenFS ?

Thanks for the assistance

**Comment by chinonso098** [comment]
Thank you very much for the reply.  I will give it a whirl and let you know

**Comment by chinonso098** [comment]
@dr-vortex 

I get the error msg  

> No overload matches this call.
  Overload 2 of 2, '(config: Partial<Configuration<ConfigMounts>>): Promise<void>', gave the following error.
    Object literal may only specify known properties, and 'backend' does not exist in type 'Partial<Configuration<ConfigMounts>>'.ts(2769)

<img width="1078" alt="Screenshot 2024-06-06 at 1 51 49 PM" src="https://github.com/zen-fs/core/assets/14144437/0ea63a25-f097-4f60-a67c-62f63fa16e90">

**Comment by dr-vortex** [comment]
The automatic type acquisition failed in this case. I'm not sure what causes it to fail. You can either add a type parameter (`await configure<typeof Overlay>(...)` or use the second overload: 

```ts
import { configure, FS, Overlay, Fetch } from '@zenfs/core';
import { IndexedDB } from '@zenfs/dom';

await configure({
    mounts: {
        '/': {
            backend: Overlay,
            readable: {
                backend: Fetch,
                index: indexPathOrObject,
            },
            writable: {
                backend: IndexedDB,
                storeName: 'fs-cache'
            }
        }
    }
});
```

**Comment by chinonso098** [comment]
@dr-vortex  

I added a type parameter 

`private async  FSSetup(){

        await configure<typeof Overlay>({
            backend: Overlay,
            readable: {
                backend: Fetch,
                index: osDriveFileSystemIndex,
            },
            writable: {
                backend: IndexedDB,
                storeName: 'fs-cache'
            }
        });
    }`

but I got the error msg 

> No overload matches this call.
  Overload 2 of 2, '(config: Partial<Configuration<{ readonly name: "Overlay"; readonly options: { readonly writable: { readonly type: "object"; readonly required: true; readonly description: "The file system to write modified files to."; }; readonly readable: { ...; }; }; readonly isAvailable: () => boolean; readonly create: (options: OverlayOptions) => OverlayFS; }>>): Promise<...>', gave the following error.
    Object literal may only specify known properties, and 'backend' does not exist in type 'Partial<Configuration<{ readonly name: "Overlay"; readonly options: { readonly writable: { readonly type: "object"; readonly required: true; readonly description: "The file system to write modified files to."; }; readonly readable: { ...; }; }; readonly isAvailable: () => boolean; readonly create: (options: OverlayO...'.ts(2769)

<img width="1064" alt="Screenshot 2024-06-06 at 2 25 54 PM" src="https://github.com/zen-fs/core/assets/14144437/1a888746-a2af-4082-9ee0-349aeae74502">



Then I tried the second option

<img width="1028" alt="Screenshot 2024-06-06 at 2 29 08 PM" src="https://github.com/zen-fs/core/assets/14144437/66196669-fcd5-4285-b74b-a31f1da8b19d">

but I got the error message 

> No overload matches this call.
  Overload 1 of 2, '(config: MountConfiguration<Backend<FileSystem, object>>): Promise<void>', gave the following error.
    Object literal may only specify known properties, and 'mounts' does not exist in type 'MountConfiguration<Backend<FileSystem, object>>'.ts(2769)



But when I try the second option with type parameter, the error msg clear up.


<img width="1121" alt="Screenshot 2024-06-06 at 2 32 07 PM" src="https://github.com/zen-fs/core/assets/14144437/41f4f983-3bb9-488d-95ff-31cfebb60c99">

**Comment by chinonso098** [comment]
Multiple error thrown when I try to execute the programs

<img width="1177" alt="Screenshot 2024-06-06 at 3 42 43 PM" src="https://github.com/zen-fs/core/assets/14144437/403b9269-61c6-4109-8934-5d5860f482ed">

<img width="1197" alt="Screenshot 2024-06-06 at 3 43 44 PM" src="https://github.com/zen-fs/core/assets/14144437/8b2bbf4d-29fa-4c1c-b3e1-4ba2029ad268">

<img width="1198" alt="Screenshot 2024-06-06 at 3 44 35 PM" src="https://github.com/zen-fs/core/assets/14144437/cb2f8aa0-b803-4dff-b5ac-230aef9355dc">

<img width="1177" alt="Screenshot 2024-06-06 at 3 45 18 PM" src="https://github.com/zen-fs/core/assets/14144437/a4008735-52d9-48f6-b5f0-b956ebbdaa65">

........

any idea on what could be the cause

**Comment by dr-vortex** [comment]
Make sure you have both `@zenfs/core` and `@zenfs/dom`.

**Comment by dr-vortex** [comment]
Yes, you will need to use a modern target. Is there any other issues I can help you with?

**Comment by james-pre** [comment]
Closing since I believe the issue has been resolved. Please reopen if you still need help.
