### ISSUE TITLE
Backslashes in index generated on Windows

### ISSUE THREAD

**Issue by 1j01** [zen-fs/core#85]
On Windows, the `make-index` command outputs JSON with entries having backslashes in the keys, e.g.:
```js
{
  "version": 1,
  "entries": {
    "/.gitattributes": { ... }
    "/.github\\workflows\\playwright.yml": { ... },
    "/.github\\workflows": { ... },
    ...
  },
}
```
When the generated index with `FetchFS`, it lists every file in the folder structure as if it were a file at the root, whose name contains backslashes.

For example, running `ZenFS.fs.readdirSync("/")` I got:
```js
Array(4203) [ ".gitattributes", ".github\\workflows\\playwright.yml", ".github\\workflows", ".github", ".gitignore", "android-chrome-192x192.png", "android-chrome-256x256.png", "apple-touch-icon.png", "audio\\CHIMES.WAV", "audio\\CHORD.WAV", … ]
```
Where I expected:
```js
Array(37) [ "programs", ".gitattributes", ".github", ".gitignore", "android-chrome-192x192.png", "android-chrome-256x256.png", "apple-touch-icon.png", "audio", "browserconfig.xml", "classic.css", … ]
```

A simple fix is to use `fixSlash` already in `make-index.js` each place where `entries.set` is called.

However, it may be best to also make the logic that _consumes_ the index more robust by handling both types of path separators... just in case someone creates their own filesystem index, I suppose.

**Comment by james-pre** [comment]
I believe it would best to normalize the paths *before* placing them into the index. This is easily accomplished by using `relative` and `resolve` from `node:path/posix` instead of `node:path`.
