### ISSUE TITLE
Missing Modules

### ISSUE THREAD

**Issue by chinonso098** [zen-fs/core#94]
Hi there, I just got back again to switching from BrowserFs to ZenFs. I am currently running Angular 18 & Node v22.2.0

I get the follwing errors when  the app tries to build. Any ideas on what could be the cause ?

![image](https://github.com/user-attachments/assets/5c78a2b7-d04f-4caf-9c07-ebbc956bf835)

Thanks for the assist.

**Comment by james-pre** [comment]
@chinonso098 What's version of `@zenfs` packages are you using?

**Comment by chinonso098** [comment]
@james-pre     
 "@zenfs/core": "^0.16.1",   
 "@zenfs/dom": "^0.2.14",

**Comment by chinonso098** [comment]
Quick update. In my  tsconfig.json file, I updated the module and the moduleResolution.

from:
"module": "es2022",
"moduleResolution": "node",

to:
"module": "esnext",
"moduleResolution": "bundler",


I would have gone (Node16, or NodeNext) forthe module and the moduleResolution, but that appears to cause issues with Angular imports like (import { AfterViewInit, OnInit,OnDestroy, Component, ElementRef, ViewChild} from '@angular/core';)


This is the only File that can't be found.

![image](https://github.com/user-attachments/assets/20a298f4-667b-4c4e-bd32-587fe27b71b9)


I did a search, and there is only one reference to it: in the locked.d.ts file

![image](https://github.com/user-attachments/assets/77cf15e5-fc07-463a-a849-a4c5a773664a)


Any idea on where I can find it ?  


thanks for the assist

**Comment by chinonso098** [comment]
if I click on the 
 import '../polyfills.js'
 
![image](https://github.com/user-attachments/assets/58eedd72-eb97-474e-aebe-d6a3da4a3745)

it brings me here

![image](https://github.com/user-attachments/assets/d0ee69aa-d996-433c-84ae-7cf24ca1210b)

could that be the cause of the issue.

other import links lead to .d.ts  files have actual export content

like the  cred.js import for example, the link leads to a cred.d.ts files that exports the Cred interface

![image](https://github.com/user-attachments/assets/e4aa705c-4aff-4214-9178-7f173b119327)

**Comment by james-pre** [comment]
@chinonso098 `PromiseWithResolvers` should be provided in `ESNext.Promise` (TS lib). Please ensure you include that in the TS "lib" config.

**Comment by chinonso098** [comment]
You are the man!!! Thank you very much.  It builds successfully

**Comment by james-pre** [comment]
@chinonso098 Glad to help! I hope you enjoy using ZenFS. Please let me know if you have any problems.
